ENVIRONMENT:
  max_episode_steps: 500
  
SIMULATOR:
  type: Habitat-Sim
  action_space_config: v0
  rgb_sensor:
    width: 256
    height: 256
  depth_sensor:
    width: 256
    height: 256
    
TASK:
  type: Nav-v0
  success_distance: 0.2
  sensors: ['rgb_sensor', 'depth_sensor']
  measurements: ['distance_to_goal', 'success']
  
DATASET:
  type: PointNav-v1
  split: train
  data_path: "data/datasets/pointnav/habitat-test-scenes/v1/{split}/{split}.json.gz"
  scenes_dir: "data/scene_datasets/"